### ISSUE TITLE
Hey, I can`t download the plugin!

### ISSUE THREAD

**Issue by Fumiyoo** [Alex1607/AntiAntiMover#1]

**Comment by Alex1607** [comment]
The download on the Sinusbot website is working fine for me. Are you logged in?
If you still cant download the file there or you dont want to create a account you can also just download this file from github: https://github.com/Alex1607/AntiAntiMover/blob/master/AntiAntiMover.js
Its exactly the same file as you would get if you would download it on the Sinusbot site.
